# Generated by Django 3.2.4 on 2021-06-25 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('RT', 'Restaurant'), ('PL', 'Place'), ('CP', 'Complement'), ('QT', 'Question'), ('RQ', 'Request'), ('WR', 'Worry'), ('RP', 'Report'), ('EL', 'Else')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
